### ISSUE TITLE
魔法植物成长/收获时，树苗处的方块在数据库中没有正确更新。

### ISSUE THREAD

**Issue by XXY233** [ybw0014/ExoticGarden-CN#26]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

- 魔法植物催熟后，树苗处的方块数据没有正确保存。
- 魔法植物采摘后，树苗处的方块数据没有正确保存。

会导致以下问题：
1. 服务器重启后树苗会向下平移1格并吞掉所在的方块

### 复现步骤

1. 种下一颗钻石魔法植物树苗
2. 使用骨粉对着他一直右键
3. 触发bug

### 预期行为

数据都应正确保存。

### 服务端软件

Paper

### Minecraft 版本

1.20.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

04fad91-DEV

### 插件版本

ExoticGarden-Build 15 zh-CN(ybw0014) (git 1aa87ca)

**Comment by XXY233** [comment]
有一个nbt，可以决定树叶离开原木是否枯萎，我觉得可以利用一下。这样也不用监听树叶枯萎事件了😀
https://minecraft.fandom.com/zh/wiki/%E6%A0%91%E5%8F%B6#:~:text=%E6%A0%91%E5%8F%B6%E6%98%AF%E5%90%A6%E5%90%AB%E6%B0%B4%E3%80%82-,persistent,-false

**Comment by XXY233** [comment]
https://github.com/SlimefunGuguProject/ExoticGarden/blob/master/src/main/java/io/github/thebusybiscuit/exoticgarden/listeners/PlantsListener.java#L211C2-L212
这里似乎存在奇怪的竞争操作，在植物被催熟后，游戏中是记录正确的魔法植物精华，但是数据库里的记录没有按照预期更新，还是原来的树苗：
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/1c1cce71-554e-48ce-a2ca-bd948ea22349)
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/4fadc71b-48a2-4240-953a-f26bee3cb7d1)

**Comment by XXY233** [comment]
经过测试，Slimefun 230817-68c243b-Insider 中已不存在此问题。

**Comment by XXY233** [comment]
测试环境：
- 异域花园版本为最新的官方构建：https://builds.guizhanss.com/SlimefunGuguProject/ExoticGarden/master/builds/15
- 粘液科技版本为 slimefun-230817-68c243b-Insider

今天晚上我又测试了一下，情况有些糟糕。上面提到的问题还是会发生，只是概率比以前低了一点点。
并且又多了一个新的问题，在收获植物时，数据库里的数据有几率不更新（收获之后实际应该为“DIAMOND_PLANT”，但记录的值却是“DIAMOND_ESSENCE”）：
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/cc6e55f3-0455-484b-a98a-d5d518f38601)
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/9b675045-1b36-4fcd-a1b7-46856f81b610)

**Comment by StarWishsama** [comment]
我刷了快六组精华都没复现🤔

**Comment by XXY233** [comment]
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/6cc7596a-2c75-4181-ab54-8b2e25b02841)
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/6591051a-49ad-4b93-9681-ef204c7758d7)
要不我录个视频😭

**Comment by XXY233** [comment]
> 我刷了快六组精华都没复现🤔

这是我触发bug的过程，只用了几十秒：https://www.bilibili.com/video/BV1Xh4y127fN/

**Comment by StarWishsama** [comment]
复现不了😭数据库所有操作都是进队列执行的，应该不存在漏的问题
你可以试着开调试模式的时候复现一次 (/sf debug slimefun_database)，然后附上 debug 时间的那段服务器 log。

**Comment by XXY233** [comment]
我刚刚试了最新的粘液科技（230909-0e66cf2），成功复现

log：https://paste.gg/p/anonymous/1b38f942ea634bc2ad1b0bcd16538867
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/a8549ff2-2624-4e25-a0e3-e86b3d953b28)

**Comment by StarWishsama** [comment]
`[20:37:21] [SF-Database-Thread #2/INFO]: [Slimefun] [DEBUG slimefun_database] Prepare execute sql statement: INSERT OR IGNORE INTO block_record (chunk, loc, sf_id) VALUES ('world;-19:10', 'world;-291:80:166', 'NETHERITE_PLANT');`

如果这就是你能触发后能看见的最后一句，那不应该啊🤔
写入操作实际上是有进行的。

**Comment by XXY233** [comment]
> `[20:37:21] [SF-Database-Thread #2/INFO]: [Slimefun] [DEBUG slimefun_database] Prepare execute sql statement: INSERT OR IGNORE INTO block_record (chunk, loc, sf_id) VALUES ('world;-19:10', 'world;-291:80:166', 'NETHERITE_PLANT');`
> 
> 如果这就是你能触发后能看见的最后一句，那不应该啊🤔 写入操作实际上是有进行的。

我也觉得很奇怪，服务器和我本地测试的电脑都可以触发这个BUG。我也不知道是哪里出了问题

**Comment by StarWishsama** [comment]
稍后推送一版包含更多 debug log 的 insider 版本，请尝试重做先前的操作并提供 log

**Comment by StarWishsama** [comment]
顺便附一下你的 block-storage.yml 配置

**Comment by XXY233** [comment]
log: https://paste.gg/p/anonymous/9f92098fa0884fd38b7cb07785c1ae14
block-storage.yml: https://paste.gg/p/anonymous/0ec6047ee7d1477fab3a748b855b1843
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/46647646/51b97c92-ef7d-4058-89c3-b27c7c0b408a)

**Comment by StarWishsama** [comment]
![00bf721fc39ca2df6d00d474835edbb7](https://github.com/SlimefunGuguProject/ExoticGarden/assets/25561848/15f4da50-aeb7-4ce1-a8fc-3cfa01bfb6b6)
可以复现，但是在下一个 tick 会自动恢复。

**Comment by XXY233** [comment]
> ![00bf721fc39ca2df6d00d474835edbb7](https://user-images.githubusercontent.com/25561848/267282036-15f4da50-aeb7-4ce1-a8fc-3cfa01bfb6b6.png) 可以复现，但是在下一个 tick 会自动恢复。

我这边服务器和本地测试直到关服后都不会恢复，就导致有莫名其妙的bug（比如再次开服时植物会向下移动1格并吞掉方块）

**Comment by StarWishsama** [comment]
已复现。
![image](https://github.com/SlimefunGuguProject/ExoticGarden/assets/25561848/542fb66a-1636-4fb2-8d65-438d37f485fc)

**Comment by StarWishsama** [comment]
调低延迟写入的 delay 试试？

**Comment by StarWishsama** [comment]
更新新版本试试

**Comment by XXY233** [comment]
好的，我会晚点测试

**Comment by StarWishsama** [comment]
230912-1f66dad-Insider

**Comment by XXY233** [comment]
我下载到的版本是 230912-823dbfc-Insider，需要调低延迟写入的 delay 吗？（我测试时没有调低）

**Comment by XXY233** [comment]
我测试时暂时没有发现这个bug，我会把插件装到服务器里，看看玩家还会不会遇到这个问题。

**Comment by StarWishsama** [comment]
> 我测试时暂时没有发现这个bug，我会把插件装到服务器里，看看玩家还会不会遇到这个问题。

不用，下你能下到的最新版就行

**Comment by XXY233** [comment]
换了最新版粘液科技之后，服务器一直刷这个报错：
```
[21:03:52 ERROR]: [Slimefun] Exception thrown while executing write task:
[21:03:52 WARN]: java.lang.IllegalArgumentException: Condition is required for update statement!
[21:03:52 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.adapter.sqlite.SqliteAdapter.setData(SqliteAdapter.java:62)
[21:03:52 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.controller.ADataController.lambda$scheduleWriteTask$1(ADataController.java:91)
[21:03:52 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.task.QueuedWriteTask.run(QueuedWriteTask.java:19)
[21:03:52 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:03:52 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:03:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:03:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:03:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
```
[21:04:41 ERROR]: [Slimefun] Exception thrown while executing write task:                                                                   [21:04:41 WARN]: java.lang.IllegalArgumentException: Condition is required for update statement!                                            [21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.adapter.sqlite.SqliteAdapter.setData(SqliteAdapter.java:62)                                                                                                                 [21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.controller.ADataController.lambda$scheduleWriteTask$1(ADataController.java:91)                                                                                              [21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.task.QueuedWriteTask.run(QueuedWriteTask.java:19)
[21:04:41 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:04:41 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:04:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:04:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:04:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:04:41 WARN]: java.lang.IllegalArgumentException: Condition is required for update statement!
[21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.adapter.sqlite.SqliteAdapter.setData(SqliteAdapter.java:62)
[21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.controller.ADataController.lambda$scheduleWriteTask$1(ADataController.java:91)
[21:04:41 WARN]:        at Slimefun-230912-823dbfc-Insider.jar//com.xzavier0722.mc.plugin.slimefun4.storage.task.QueuedWriteTask.run(QueuedWriteTask.java:19)
[21:04:41 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:04:41 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:04:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:04:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:04:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by StarWishsama** [comment]
更新稍后推送的新版本🤔

**Comment by StarWishsama** [comment]
新版还能复现吗

**Comment by XXY233** [comment]
复现不出来，应该已经被修复了。
